In [11]:
import numpy as np
sqrt_c = np.linspace(np.sqrt(0.1*8.2*0.001), np.sqrt(8.2*0.001), 5)
sqrt_c

array([0.02863564, 0.04411519, 0.05959475, 0.0750743 , 0.09055385])

In [12]:
c = sqrt_c**2

In [13]:
c

array([0.00082   , 0.00194615, 0.00355153, 0.00563615, 0.0082    ])

In [14]:
import numpy as np
sqrt_c = np.linspace(np.sqrt(1.25*8.2*0.001), np.sqrt(3*8.2*0.001), 5)
sqrt_c

array([0.10124228, 0.11514268, 0.12904308, 0.14294347, 0.15684387])

In [15]:
c1 = sqrt_c**2
c1

array([0.01025   , 0.01325784, 0.01665212, 0.02043284, 0.0246    ])

In [18]:
C = np.concatenate((c, c1), axis=0)

In [19]:
C

array([0.00082   , 0.00194615, 0.00355153, 0.00563615, 0.0082    ,
       0.01025   , 0.01325784, 0.01665212, 0.02043284, 0.0246    ])

In [20]:
vol = C*25/40*1000
vol

array([ 0.5125    ,  1.21634399,  2.21970865,  3.52259399,  5.125     ,
        6.40625   ,  8.28614806, 10.40757241, 12.77052306, 15.375     ])

In [22]:
lg_c1 = np.linspace(np.log10(0.02*8.2*0.001), np.log10(8.2*0.001), 9)
lg_c1

array([-3.78515615, -3.5727849 , -3.36041365, -3.1480424 , -2.93567115,
       -2.7232999 , -2.51092865, -2.2985574 , -2.08618615])

In [23]:
c1 = 10**lg_c1
c1

array([0.000164  , 0.00026743, 0.0004361 , 0.00071114, 0.00115966,
       0.00189104, 0.00308369, 0.00502855, 0.0082    ])

In [24]:
lg_c2 = np.linspace(np.log10(1.25*8.2*0.001), np.log10(2.5*8.2*0.001), 3)
lg_c2

array([-1.98927613, -1.83876114, -1.68824614])

In [25]:
c2 = 10**lg_c2

In [26]:
c2

array([0.01025   , 0.01449569, 0.0205    ])

In [27]:
c_sigma = np.concatenate((c1, c2), axis=0)
c_sigma

array([0.000164  , 0.00026743, 0.0004361 , 0.00071114, 0.00115966,
       0.00189104, 0.00308369, 0.00502855, 0.0082    , 0.01025   ,
       0.01449569, 0.0205    ])

In [28]:
vol_sigma = c_sigma*10/4*1000

In [29]:
vol_sigma

array([ 0.41      ,  0.66858266,  1.09025066,  1.7778602 ,  2.8991378 ,
        4.72759331,  7.70923634, 12.57137005, 20.5       , 25.625     ,
       36.23922254, 51.25      ])